server:
  port: 8080
spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/bookinghotel
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect